### ISSUE TITLE
Same location can be saved multiple times

### ISSUE THREAD

**Issue by baherami** [Metatavu/megasense-data-portal-ui#85]
Save location adds multiple same locations to the saved location list if user continues to add them.

**Comment by Daniilmass** [comment]
The check should be probably done in the backend.But since we already have a list of saved locations in the frontend, it should be implemented in the frontend by comparing the new saved location coordinates to the existing saved locations coordinated. If there is a match, a popup should say that this location already exists (and maybe a name of the existing location)
